package com.catolicasc.org.br.view;

import java.io.File;
import javax.swing.JTextField;

import com.catolicasc.org.br.KmpA;
import com.catolicasc.org.br.LeituraDeLinhas;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author israel.cadorin
 */
public class BrowserView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public BrowserView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabelTesxtoBusca = new javax.swing.JLabel();
        jTextFieldTextoBusca = new javax.swing.JTextField();
        jButtonBusca = new javax.swing.JButton();
        jProgressTempoDeBusca = new javax.swing.JProgressBar();
        jLabelLocalArquivo = new javax.swing.JLabel();
        jTextFieldLocalArquivo = new javax.swing.JTextField();
        jButtonBrowser = new javax.swing.JButton();
        jLabelResposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTesxtoBusca.setText("Digite o texto de busca:");
        jLabelTesxtoBusca.setToolTipText("");

        jTextFieldTextoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTextoBuscaActionPerformed(evt);
            }
        });

        jButtonBusca.setText("Buscar Por Padrão");
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        jLabelLocalArquivo.setText("Local do Arquivo:");

        jButtonBrowser.setText("Browser...");
        jButtonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabelTesxtoBusca))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLocalArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLocalArquivo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBrowser))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTextoBusca)
                            .addComponent(jButtonBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressTempoDeBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTesxtoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTextoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLocalArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextFieldLocalArquivo))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonBusca)
                .addGap(23, 23, 23)
                .addComponent(jProgressTempoDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextFieldTextoBuscaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void jButtonBrowserActionPerformed(java.awt.event.ActionEvent evt) {                                               

        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);
        
        if(i == 1) {
            jTextFieldLocalArquivo.setText(" ");
        }else {
            File arquivo = file.getSelectedFile();
            jTextFieldLocalArquivo.setText(arquivo.getPath());
        }
    }                                              

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	String busca = jTextFieldTextoBusca.getText();
    	String caminhoDoArquivo = jTextFieldLocalArquivo.getText();
    	
    	String resposta = "Problema não encontrado!";
    	
    	if(busca.isEmpty() == false) {
    		resposta = "Tem texto!";
    		if(caminhoDoArquivo.isEmpty() == false) {
    			resposta = "Tem diretório do arquivo!";
    			LeituraDeLinhas arquivo = new LeituraDeLinhas(caminhoDoArquivo);
    			arquivo.readerFile();
    			String conteudoDoArquivo = arquivo.getText();
    			
    			
    			
    		}else {
    			resposta = "Não tem diretório do arquivo!";
    		}
    	}else {
    		resposta = "Texto de Busca não foi inserido!";
    	}
    
        	
    	//}
    		
    	//
		//	
    	
    	//	KmpA kmp = new KmpA(busca, conteudoDoArquivo);
    	//	kmp.buscar();
    	//	resposta = kmp.getResposta();
    	
    	//    	if( resposta == null ) {
    		//	kmp.setResposta("Não encontrado!");
        	//        	resposta = kmp.getResposta();
//    	}
    		
    	jLabelResposta.setText(resposta);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBrowser;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JLabel jLabelLocalArquivo;
    private javax.swing.JLabel jLabelResposta;
    private javax.swing.JLabel jLabelTesxtoBusca;
    private javax.swing.JProgressBar jProgressTempoDeBusca;
    private javax.swing.JTextField jTextFieldLocalArquivo;
    private javax.swing.JTextField jTextFieldTextoBusca;
    // End of variables declaration                   
}